kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080 # This is the NodePort your service will use.
    hostPort: 80         # This is the port you will access on your VM's external IP.
    protocol: TCP
- role: worker
- role: worker